name: On Release Published

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print release info
        run: |
          echo "Release published!"
          echo "Tag: ${{ github.ref }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release body: ${{ github.event.release.body }}"